### ISSUE TITLE
blog + strategies template redesign

### ISSUE THREAD

**Issue by peteratomic** [resonatecoop/resonate-frontend#1]
Need the footer of the blog + strategies templates redone according to this new design. 
![blog - boxes](https://cloud.githubusercontent.com/assets/7466182/20701460/6230d270-b613-11e6-9077-7a75a3bf4f8a.png)

blog is single.php
strategies is single-strategies.php
3objects-horizontal.png is in the images folder (in the theme).

**Comment by blushi** [comment]
moved to https://gitlab.resonate.ninja/resonate/resonate_ninja/issues/1
