### ISSUE TITLE
clean up this repository

### ISSUE THREAD

**Issue by peteratomic** [resonatecoop/resonate-frontend#2]
Think this repo was for the wordpress site set up by another dev long ago. Could it be converted into use for front end issues? Want to start adding more stuff here to get help.

**Comment by peteratomic** [comment]
Think this repo was for the wordpress site set up by another dev long ago. Could it be converted into use for front end issues? Want to start adding more stuff here to get help.

**Comment by peteratomic** [comment]
https://github.com/resonatecoop/resonate-frontend

**Comment by blushi** [comment]
Yes sure, we could use this repo as a global place for front end issues. Adding some wiki or a README.md at least would be a good start to point new comers into the right direction.

**Comment by peteratomic** [comment]
Maybe Patrick could write something based on the setup we've got? Not sure if it's in a position to be shared publicly or not. Could also write a short intro telling folks who to get in touch with. I leave it to Marie + Patrick to decide!

**Comment by blushi** [comment]
moved to gitlab.resonate.ninja

**Comment by blushi** [comment]
moved to gitlab.resonate.ninja
