### ISSUE TITLE
label profile page

### ISSUE THREAD

**Issue by peteratomic** [resonatecoop/resonate-frontend#3]
Finish work started on label version of new design. Includes artists and a player incorporating all music from the label. https://resonate.ninja/profile/178/

**Comment by peteratomic** [comment]
Tim, Patrick AKA @dubfractal in Slack is working on those, so feel free to reach out to him directly.

**Comment by blushi** [comment]
moved to https://gitlab.resonate.ninja/resonate/resonate_ninja/issues/2
