### ISSUE TITLE
change country to city in profiles

### ISSUE THREAD

**Issue by peteratomic** [resonatecoop/resonate-frontend#4]
Here's where it gets tricky. Ideally this would be a tag. But I'm not 100% sure we can add a totally different tag without messing up the genres tag + search functionality. Ideally you'd want to be able to click on the city to find all the artists in that area. Have a request from one artist about this already and thought it could go a long way to start getting more local promotion together by connecting people.

**Comment by blushi** [comment]
moved to https://gitlab.resonate.ninja/resonate/resonate_ninja/issues/3

**Comment by blushi** [comment]
moved to https://gitlab.resonate.ninja/resonate/resonate_ninja/issues/3
